Repository collabhq/collab-service, pull requests merged in 2019-04, with the labels that each got.

#14 Refactored code to workspace from room
  src/main/java/com/puffnote/backendservice/controller/NoteController.java
  src/main/java/com/puffnote/backendservice/controller/NoteControllerImpl.java
  src/main/java/com/puffnote/backendservice/controller/RoomControllerImpl.java
  src/main/java/com/puffnote/backendservice/controller/WorkspaceController.java
  src/main/java/com/puffnote/backendservice/controller/WorkspaceControllerImpl.java
  src/main/java/com/puffnote/backendservice/model/NoteOperationObject.java
  src/main/java/com/puffnote/backendservice/model/Workspace.java
  src/main/java/com/puffnote/backendservice/repository/RoomRepository.java
  src/main/java/com/puffnote/backendservice/repository/WorkspaceRepository.java
  src/main/java/com/puffnote/backendservice/service/NoteService.java
  src/main/java/com/puffnote/backendservice/service/NoteServiceImpl.java
  src/main/java/com/puffnote/backendservice/service/RoomService.java
  src/main/java/com/puffnote/backendservice/service/RoomServiceImpl.java
  src/main/java/com/puffnote/backendservice/service/UserService.java
  src/main/java/com/puffnote/backendservice/service/UserServiceImpl.java
  src/main/java/com/puffnote/backendservice/service/WorkspaceService.java
  src/main/java/com/puffnote/backendservice/service/WorkspaceServiceImpl.java
Labels: refactoring

#16 Add logstash config for ELK based logging
  .gitignore
  logstash.conf
  src/main/java/com/puffnote/backendservice/BackendServiceApplication.java
  src/main/java/com/puffnote/backendservice/configuration/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: enhancement

#17 Remove User and Note references correctly ( Fixes #15 )
  .gitignore
  src/main/java/com/puffnote/backendservice/configuration/WebSecurityConfig.java
  src/main/java/com/puffnote/backendservice/controller/NoteController.java
  src/main/java/com/puffnote/backendservice/service/UserServiceImpl.java
  src/main/java/com/puffnote/backendservice/service/WorkspaceServiceImpl.java
Labels: bug

#20 Travis AWS Deployment
  .travis.yml
  pom.xml
  src/main/resources/application.properties
Labels: enhancement

#21 New users join into an existing workspace
  src/main/java/com/puffnote/backendservice/controller/WorkspaceController.java
  src/main/java/com/puffnote/backendservice/controller/WorkspaceControllerImpl.java
Labels: enhancement

#25 Sync webapp and service for new user join into workspace and filter notes
  src/main/java/com/collab/backendservice/controller/NoteController.java
  src/main/java/com/collab/backendservice/controller/NoteControllerImpl.java
  src/main/java/com/collab/backendservice/controller/WorkspaceControllerImpl.java
  src/main/java/com/collab/backendservice/model/SocketResponse.java
  src/main/java/com/collab/backendservice/util/Constants.java
Labels: enhancement

#26 Refactor SocketResponse and Custom Exception support
  src/main/java/com/collab/backendservice/controller/NoteControllerImpl.java
  src/main/java/com/collab/backendservice/exception/CollabException.java
  src/main/java/com/collab/backendservice/exception/CollabRuntimeException.java
  src/main/java/com/collab/backendservice/model/SocketResponse.java
Labels: enhancement
