Repository collabhq/collab-service, pull requests merged in 2019-05, with the labels that each got.

#27 Auth
  pom.xml
  src/main/java/com/collab/backendservice/component/JwtAuthorizationFilter.java
  src/main/java/com/collab/backendservice/component/JwtTokenBuilder.java
  src/main/java/com/collab/backendservice/configuration/EnvironmentConfig.java
  src/main/java/com/collab/backendservice/configuration/WebSecurityConfig.java
  src/main/java/com/collab/backendservice/configuration/WebSocketConfig.java
  src/main/java/com/collab/backendservice/controller/NoteController.java
  src/main/java/com/collab/backendservice/controller/NoteControllerImpl.java
  src/main/java/com/collab/backendservice/controller/WorkspaceControllerImpl.java
  src/main/java/com/collab/backendservice/model/User.java
  src/main/java/com/collab/backendservice/service/UserService.java
  src/main/java/com/collab/backendservice/service/UserServiceImpl.java
  src/main/java/com/collab/backendservice/util/Constants.java
  src/main/resources/application.properties
Labels: bug, enhancement

#32 Fix alpha testing issues
  src/main/java/com/collab/backendservice/ApplicationStartup.java
  src/main/java/com/collab/backendservice/component/DeleteWorkspaceTask.java
  src/main/java/com/collab/backendservice/configuration/WebSocketConfig.java
  src/main/java/com/collab/backendservice/controller/WorkspaceControllerImpl.java
  src/main/java/com/collab/backendservice/model/User.java
  src/main/java/com/collab/backendservice/model/Workspace.java
Labels: refactoring

#34 Verify if workspace exists on socket connection
  src/main/java/com/collab/backendservice/component/JwtAuthorizationFilter.java
  src/main/java/com/collab/backendservice/configuration/WebSocketConfig.java
  src/main/java/com/collab/backendservice/controller/WorkspaceController.java
  src/main/java/com/collab/backendservice/controller/WorkspaceControllerImpl.java
Labels: enhancement

#35 Update release branch
  src/main/java/com/collab/backendservice/component/JwtAuthorizationFilter.java
  src/main/java/com/collab/backendservice/configuration/WebSocketConfig.java
  src/main/java/com/collab/backendservice/controller/WorkspaceController.java
  src/main/java/com/collab/backendservice/controller/WorkspaceControllerImpl.java
Labels: enhancement
